// GSTR-1 FORMAT LOCK.
//
// The July 2026 return was accepted by the GST Portal (ref
// 7634d93b-a07a-4f1d-a995-7dc75b8a4765, and again as
// d915821e-bb31-4924-9085-aeac8137a537). That file's STRUCTURE is now the
// canonical production format. Monthly data changes; the format does not.
//
// Getting there took twelve uploads, because the Portal answers a structural
// problem with one generic sentence and names no field. Each defect below was
// isolated by adding one section at a time to a known-accepted baseline:
//
//   + b2cl                          accepted  6f7ed599
//   + cdnr                          REFUSED   4a091bb2   -> missing inv_typ
//   + cdnr with inv_typ:"R"         accepted  065ee200
//   + cdnur                         accepted  7c33b553
//   + exp (alphanumeric sbnum)      REFUSED   0c657af6   -> sbnum must be digits
//   + exp with nested itms          REFUSED   118344b3   -> flat was right all along
//   + exp (numeric sbnum, flat)     accepted  bc791dd3
//   + at                            accepted  bff59a63
//   + atadj                         REFUSED   925b681d   -> wrong key name
//   + txpd (same bytes, renamed)    accepted  57a4038d
//   + nil — the complete return     accepted  7634d93b
//
// These tests exist so none of that has to be discovered twice. They assert
// STRUCTURE, never business values: no amount, date, GSTIN or invoice number
// from any real return appears here or in the fixture.
//
// The fixture is generated by the exporter itself over deterministic dummy
// input, so it records what the code actually produces rather than what
// someone believed it produced. If a change to the exporter is deliberate and
// the Portal has confirmed the new shape, the fixture is updated in the same
// commit — and the commit message is expected to carry the Portal reference
// that justifies it.
const test = require('node:test');
const assert = require('node:assert');
const fs = require('fs');
const path = require('path');
const { createBrowserContext, makeDataSupabase } = require('./helpers/browser-context');

const ctx = createBrowserContext();
const CANONICAL = JSON.parse(
  fs.readFileSync(path.join(__dirname, 'fixtures', 'gstr1-format-canonical.json'), 'utf8'));

// ── D. The canonical root order, stated once, in full ──────────────
// Deliberately NOT derived from the fixture: if both the payload and the
// expectation came from the same place, a reordering would satisfy both.
const CANONICAL_ROOT_ORDER = [
  'gstin', 'fp', 'version', 'hash',
  'b2b', 'b2cl', 'b2cs', 'cdnr', 'cdnur', 'exp', 'at', 'txpd', 'nil', 'hsn', 'doc_issue'
];
const CANONICAL_VERSION = 'GST3.1.7';
const CANONICAL_HASH = 'hash';

// ── Dummy input, the same set the fixture was generated from ───────
// Every value is invented. The GSTIN check digits are computed by the app's
// own algorithm so they pass validateGstin() without being real numbers.
const US = 'canonical-user';
const mint = (state, pan, ent = '1') => {
  const first14 = `${state}${pan}${ent}Z`;
  return first14 + ctx.gstinCheckDigit(first14);
};
const OWN = mint('33', 'AAAAA0000A');
const REG_TN = mint('33', 'BBBBB1111B');
const REG_KL = mint('32', 'CCCCC2222C');

const money = (tx, rate, inter) => {
  const gst = +(tx * rate / 100).toFixed(2);
  return inter
    ? { tx, rate, gst, igst: gst, cgst: 0, sgst: 0 }
    : { tx, rate, gst, igst: 0, cgst: +(gst / 2).toFixed(2), sgst: +(gst / 2).toFixed(2) };
};
const inv = o => ({ user_id: US, customer_name: 'Dummy Party', gst_category: 'regular',
  reverse_charge: false, invoice_source: 'manual', ...o });
const line = o => ({ user_id: US, product_name: 'Dummy Product', hsn_code: '84388090',
  unit: 'NOS', gst_treatment: 'taxable', cess_rate: 0, cess_amount: 0, ...o });

const m1 = money(10000, 18, false);    // b2b
const m2 = money(20000, 18, true);     // exp
const m3 = money(300000, 18, true);    // b2cl
const m4 = money(5000, 18, false);     // b2cs
const m5 = money(7000, 0, false);      // nil

// A period that exercises all thirteen data sections at once. Anything less
// and a section's shape goes unlocked — which is how exp, at and txpd came to
// have no coverage at all before this file existed.
function canonicalTables() {
  return {
    b2b_invoices: [
      inv({ id: 'i-b2b', invoice_number: 'D-001', invoice_date: '2026-07-02',
        gst_number: REG_TN, state: 'Tamil Nadu', supply_type: 'intrastate',
        taxable_amount: m1.tx, gst_percentage: 18, gst_amount: m1.gst,
        total_amount: m1.tx + m1.gst, igst: m1.igst, cgst: m1.cgst, sgst: m1.sgst }),
      inv({ id: 'i-exp', invoice_number: 'D-002', invoice_date: '2026-07-10',
        gst_number: REG_KL, state: 'Other Territory', supply_type: 'interstate',
        export_type: 'WPAY', shipping_bill_number: '9000001',
        shipping_bill_date: '2026-07-11', port_code: 'INMAA1',
        taxable_amount: m2.tx, gst_percentage: 18, gst_amount: m2.gst,
        total_amount: m2.tx + m2.gst, igst: m2.igst, cgst: 0, sgst: 0 })
    ],
    b2c_invoices: [
      inv({ id: 'i-b2cl', invoice_number: 'D-003', invoice_date: '2026-07-12',
        gst_number: '', state: 'Karnataka', supply_type: 'interstate',
        taxable_amount: m3.tx, gst_percentage: 18, gst_amount: m3.gst,
        total_amount: m3.tx + m3.gst, igst: m3.igst, cgst: 0, sgst: 0 }),
      inv({ id: 'i-b2cs', invoice_number: 'D-004', invoice_date: '2026-07-14',
        gst_number: '', state: 'Tamil Nadu', supply_type: 'intrastate',
        taxable_amount: m4.tx, gst_percentage: 18, gst_amount: m4.gst,
        total_amount: m4.tx + m4.gst, igst: 0, cgst: m4.cgst, sgst: m4.sgst }),
      inv({ id: 'i-nil', invoice_number: 'D-005', invoice_date: '2026-07-16',
        gst_number: '', state: 'Tamil Nadu', supply_type: 'intrastate',
        taxable_amount: m5.tx, gst_percentage: 0, gst_amount: 0,
        total_amount: m5.tx, igst: 0, cgst: 0, sgst: 0 })
    ],
    invoice_items: [
      line({ id: 'l1', invoice_id: 'i-b2b', invoice_type: 'b2b', quantity: 1, rate: m1.tx,
        gst_percentage: 18, taxable_value: m1.tx, gst_amount: m1.gst,
        igst: 0, cgst: m1.cgst, sgst: m1.sgst, total_amount: m1.tx + m1.gst }),
      line({ id: 'l2', invoice_id: 'i-exp', invoice_type: 'b2b', hsn_code: '84386000',
        quantity: 2, rate: m2.tx / 2, gst_percentage: 18, taxable_value: m2.tx,
        gst_amount: m2.gst, igst: m2.igst, cgst: 0, sgst: 0, total_amount: m2.tx + m2.gst }),
      line({ id: 'l3', invoice_id: 'i-b2cl', invoice_type: 'b2c', quantity: 3, rate: m3.tx / 3,
        gst_percentage: 18, taxable_value: m3.tx, gst_amount: m3.gst,
        igst: m3.igst, cgst: 0, sgst: 0, total_amount: m3.tx + m3.gst }),
      line({ id: 'l4', invoice_id: 'i-b2cs', invoice_type: 'b2c', quantity: 1, rate: m4.tx,
        gst_percentage: 18, taxable_value: m4.tx, gst_amount: m4.gst,
        igst: 0, cgst: m4.cgst, sgst: m4.sgst, total_amount: m4.tx + m4.gst }),
      line({ id: 'l5', invoice_id: 'i-nil', invoice_type: 'b2c', hsn_code: '84386000',
        gst_treatment: 'exempt', quantity: 1, rate: m5.tx, gst_percentage: 0,
        taxable_value: m5.tx, gst_amount: 0, igst: 0, cgst: 0, sgst: 0, total_amount: m5.tx })
    ],
    cdn_notes: [
      { id: 'n1', user_id: US, note_type: 'credit', note_number: 'DN-001', note_date: '2026-07-20',
        original_invoice: 'D-001', customer_name: 'Dummy Party', gstin: REG_TN, state: 'Tamil Nadu',
        supply_type: 'intrastate', reason: 'rate revision', taxable_amount: 1000, gst_percentage: 18,
        igst: 0, cgst: 90, sgst: 90, gst_amount: 180, total_amount: 1180, supply_nature: 'regular' },
      { id: 'n2', user_id: US, note_type: 'credit', note_number: 'DN-002', note_date: '2026-07-21',
        original_invoice: 'D-003', customer_name: 'Dummy Party', gstin: '', state: 'Karnataka',
        supply_type: 'interstate', reason: 'return', taxable_amount: 2000, gst_percentage: 18,
        igst: 360, cgst: 0, sgst: 0, gst_amount: 360, total_amount: 2360, supply_nature: 'regular' }
    ],
    // place_of_supply is stored as a state NAME. The exporter is expected to
    // turn it into a two-digit code; guard N2 is the reason that matters.
    receipt_vouchers: [
      { id: 'rv1', user_id: US, document_number: 'RV-001', document_date: '2026-07-05',
        party_name: 'Dummy Party', place_of_supply: 'Tamil Nadu', supply_type: 'intrastate',
        advance_amount: 8000, gst_percentage: 18, igst: 0, cgst: 720, sgst: 720,
        total_value: 9440, adjusted_amount: 0, status: 'issued' }
    ],
    advance_adjustments: [
      { id: 'aa1', user_id: US, receipt_voucher_id: 'rv1', invoice_number: 'D-001',
        invoice_date: '2026-07-09', adjusted_on: '2026-07-09', place_of_supply: 'Tamil Nadu',
        supply_type: 'intrastate', gst_percentage: 18, adjusted_amount: 3000,
        igst: 0, cgst: 270, sgst: 270 }
    ]
  };
}

async function buildCanonical(tables = canonicalTables()) {
  ctx._supabase = makeDataSupabase(tables);
  const res = await ctx.buildGSTR1Payload(
    US, { gstin: OWN, state: 'Tamil Nadu', business_name: 'Dummy Co' }, '2026-07');
  assert.ok(!res.errors || !res.errors.length,
    'the canonical build reported errors: ' + JSON.stringify((res.errors || []).slice(0, 3)));
  // Round-tripped: the payload is built inside the browser-context realm, so
  // its objects carry that realm's prototypes and deepStrictEqual would fail
  // on identity alone. This also compares what actually gets WRITTEN.
  return JSON.parse(JSON.stringify(res.payload));
}

// Structural signature: key names and nesting, with every leaf reduced to its
// type. Two payloads with the same signature differ only in business values.
function signature(value) {
  if (Array.isArray(value)) return value.length ? [signature(value[0])] : [];
  if (value && typeof value === 'object') {
    const out = {};
    Object.keys(value).sort().forEach(k => { out[k] = signature(value[k]); });
    return out;
  }
  return typeof value;
}

// ── B. Full structure regression against the canonical fixture ─────

test('FL1. the generated payload matches the canonical structure exactly', async () => {
  const p = await buildCanonical();
  assert.deepStrictEqual(signature(p), signature(CANONICAL),
    'the GSTR-1 structure drifted from the Portal-accepted format — a field, a nesting '
    + 'level, a section name or a data type changed. If this is deliberate and the Portal '
    + 'has confirmed the new shape, update tests/fixtures/gstr1-format-canonical.json in '
    + 'the same commit and cite the Portal reference.');
});

test('FL2. root keys are in the canonical order, with nothing added or missing', async () => {
  const p = await buildCanonical();
  assert.deepStrictEqual(Object.keys(p), CANONICAL_ROOT_ORDER,
    'root key order is part of the accepted format and must not change');
  assert.deepStrictEqual(Object.keys(CANONICAL), CANONICAL_ROOT_ORDER,
    'the fixture itself drifted from the canonical order');
});

test('FL3. the serializer preserves the canonical root order', async () => {
  const p = await buildCanonical();
  const written = ctx.gstr1SerializePayload(p);
  const order = Object.keys(JSON.parse(written));
  assert.deepStrictEqual(order, CANONICAL_ROOT_ORDER,
    'gstr1SerializePayload must not reorder root keys — it sorts nested keys only');
});

test('FL4. version and hash are the accepted constants', async () => {
  const p = await buildCanonical();
  assert.strictEqual(p.version, CANONICAL_VERSION,
    'GST3.1.7 is the version the Portal accepts; GST3.2.4 was rejected for this same return');
  assert.strictEqual(p.hash, CANONICAL_HASH,
    '"hash" is the literal placeholder the official Offline Utility writes — the Portal '
    + 'computes the real digest itself, so this must not become a real hash');
});

test('FL5. all thirteen data sections are exercised, so none is left unlocked', async () => {
  const p = await buildCanonical();
  ['b2b', 'b2cl', 'b2cs', 'cdnr', 'cdnur', 'exp', 'at', 'txpd', 'nil', 'hsn', 'doc_issue']
    .forEach(k => assert.ok(k in p, `section "${k}" is missing — this fixture is meant to cover every section`));
});

test('FL6. emitWhenEmpty behaviour is unchanged: an empty section is omitted, not written as []', async () => {
  const t = canonicalTables();
  t.cdn_notes = [];
  t.receipt_vouchers = [];
  t.advance_adjustments = [];
  const p = await buildCanonical(t);
  ['cdnr', 'cdnur', 'at', 'txpd'].forEach(k =>
    assert.ok(!(k in p), `an empty ${k} must be omitted entirely, as in the accepted file`));
  ['gstin', 'fp', 'version', 'hash'].forEach(k =>
    assert.ok(k in p, `header key "${k}" is written even on a sparse return`));
});

// ── C. The five named regression guards ────────────────────────────

test('N1 — ATADJ GUARD: Table 11B is txpd, and "atadj" appears nowhere', async () => {
  const p = await buildCanonical();
  assert.ok('txpd' in p, 'Table 11B must be emitted under "txpd" (Portal ref 57a4038d)');
  assert.ok(!('atadj' in p), '"atadj" must never be a root key (Portal REFUSED it, ref 925b681d)');
  assert.ok(!JSON.stringify(p).includes('atadj'),
    '"atadj" must not appear anywhere in the written file at any depth');
});

test('N2 — ADVANCE POS GUARD: a state name becomes a two-digit POS code', async () => {
  const p = await buildCanonical();
  // The fixture stores place_of_supply as "Tamil Nadu". Emitting that verbatim
  // is what the Portal rejected before c952daf.
  [['at', p.at], ['txpd', p.txpd]].forEach(([name, section]) => {
    assert.ok(Array.isArray(section) && section.length, `${name} must carry rows in this fixture`);
    section.forEach(g => {
      assert.strictEqual(g.pos, '33',
        `${name}.pos must be the two-digit code for Tamil Nadu, got ${JSON.stringify(g.pos)}`);
      assert.match(String(g.pos), /^[0-9]{2}$/,
        `${name}.pos must be two digits, never a state name`);
    });
  });
});

test('N3 — CDNR INV_TYP GUARD: every credit/debit note carries inv_typ', async () => {
  const p = await buildCanonical();
  assert.ok(Array.isArray(p.cdnr) && p.cdnr.length, 'cdnr must carry rows in this fixture');
  p.cdnr.forEach(group => group.nt.forEach(note => {
    assert.ok('inv_typ' in note,
      `cdnr note ${note.nt_num} is missing inv_typ — the Portal refuses the file without it `
      + '(ref 4a091bb2 refused, 065ee200 accepted once it was added)');
    assert.strictEqual(typeof note.inv_typ, 'string', 'inv_typ must be a string');
  }));
});

test('N4 — EXP FLAT ITMS GUARD: exp items are flat, never num/itm_det', async () => {
  const p = await buildCanonical();
  assert.ok(Array.isArray(p.exp) && p.exp.length, 'exp must carry rows in this fixture');
  p.exp.forEach(group => group.inv.forEach(e => {
    e.itms.forEach(itm => {
      assert.deepStrictEqual(Object.keys(itm).sort(), ['csamt', 'iamt', 'rt', 'txval'],
        'exp itms rows are flat {txval, rt, iamt, csamt} — nesting them was tried and REFUSED '
        + '(ref 118344b3)');
      assert.ok(!('num' in itm), 'exp itms must not carry "num"');
      assert.ok(!('itm_det' in itm), 'exp itms must not carry "itm_det"');
    });
  }));
});

test('N5 — SHIPPING BILL DATA GUARD: a numeric sbnum is emitted unchanged, as a string', async () => {
  // A guard on the accepted behaviour only. It adds no validation and blocks
  // no export — the numeric rule is a property of the DATA, and a production
  // validator for it was deliberately not introduced here.
  const p = await buildCanonical();
  const exports_ = p.exp.flatMap(g => g.inv);
  assert.ok(exports_.length, 'exp must carry invoices in this fixture');
  exports_.forEach(e => {
    assert.strictEqual(e.sbnum, '9000001',
      'the shipping bill number must be emitted exactly as stored');
    assert.strictEqual(typeof e.sbnum, 'string',
      'sbnum is a string in the accepted format, never a number');
    assert.match(e.sbnum, /^[0-9]{3,15}$/,
      'the accepted data is 3-15 digits — an alphanumeric value was REFUSED (ref 0c657af6)');
  });
});
